### PR TITLE
Weekend Update

### PR DESCRIPTION
**Pull request by mylorik**
- added "IsWeekendAsync", returns true if voting multiplier = x2
- Fixed "GetVotersAsync" no longer required days parameter as it's obsolete, also, added created a throw exception if the bot has more than 1000 votes
- Renamed "Score" to "Points"
- added "IsWeekendAsync" unit test (passing)
- added "GetVotersAsync" unit test (passing)
- Changed naming "24h" to "12h" cooldown

### CODE REVIEW

**Comment by tonkku107** [comment]
A throw is not needed when you have more than 1000 votes, you can still get the last 1000

**Comment by mylorik** [comment]
Removed Throw.

**Comment by velddev** [comment]
I'll look over the latest commits in an hour or two, travelling to my parents for a birthday party.

**Comment by velddev** [comment]
One thing I've noticed is that you set the authentication again in GetWeekendAsync, this shouldn't have to happen. Also consider using the serialised output instead of body.Contains

**Comment by mylorik** [comment]
Alright. I will remove authorization and change .Body.Contais later today
or tomorrow

**Comment by mylorik** [comment]
HasVoted" have to be authorized.

- IsWeekend is now a non-authorized method, also I moved it into  DiscordBotListApi.cs
- using "Deserialize" instead of ".Body.Contains()"

**Pull request merged**
